# Generated by Django 4.2.17 on 2025-01-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_subject_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='about',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
