# Generated by Django 4.2.17 on 2025-01-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_address_about_email_about_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='map_url',
            field=models.URLField(blank=True, max_length=99999, null=True, verbose_name='Карта'),
        ),
    ]
