# Generated by Django 4.2.17 on 2025-01-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='about',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
