# Generated by Django 5.1.4 on 2025-01-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
