# Generated by Django 5.1.4 on 2025-01-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction',
            field=models.BooleanField(default=False, verbose_name='Аукцион'),
        ),
    ]
