# Generated by Django 5.1.4 on 2025-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='categories_image/'),
        ),
    ]
